/* Clean Route: standalone game state, mobile controls, quests and local saves. */
'use strict';
(()=>{
const C=window.CG,$=id=>document.getElementById(id),KEY='clean-route-v1';
const canvas=$('world'),sheet=$('sheet'),veil=$('veil');
let progress={version:1,records:[null,null,null],collection:[],sound:true,session:null},saveWarning=false;
try{const p=JSON.parse(localStorage.getItem(KEY));if(p&&p.version===1){if(Array.isArray(p.records)&&p.records.length===3)progress.records=p.records;if(Array.isArray(p.collection))progress.collection=p.collection.filter(x=>Number.isInteger(x)&&x>=0&&x<3);progress.sound=p.sound!==false;if(p.session&&Number.isInteger(p.session.level)&&p.session.level>=0&&p.session.level<3)progress.session=p.session;}}catch(e){/* Storage can be blocked or a previous save can be incomplete. */}
function store(){try{localStorage.setItem(KEY,JSON.stringify(progress));}catch(e){if(!saveWarning){saveWarning=true;toast('Браузер не разрешает сохранение. Можно играть без него.');}}}
const g=C.game={world:C.buildWorld(0),level:0,player:{x:480,y:1130,facing:1},active:false,mode:'home',route:[],goal:null,elapsed:0,distance:0,errors:0,order:0,effects:[],moving:false,camera:{x:240,y:650},viewW:390,viewH:780,dpr:1,scale:1,keys:new Set(),joy:{x:0,y:0},stuck:0};
Object.defineProperty(g,'bag',{get:()=>g.world.items.filter(t=>t.state===1).sort((a,b)=>(a.order||0)-(b.order||0))});
Object.defineProperty(g,'sorted',{get:()=>g.world.items.filter(t=>t.state===2).length});
const timeText=s=>`${Math.floor(s/60)}:${String(Math.floor(s%60)).padStart(2,'0')}`;
const accuracy=()=>g.sorted/(g.sorted+g.errors||1);
let toastTimer,context=null,lastUi=0,lastSave=0,lastMini=0,lastFrame=0,focusBefore=null;
function tone(freq=660){if(!progress.sound)return;try{context=context||new(window.AudioContext||window.webkitAudioContext)();if(context.state==='suspended')context.resume().catch(()=>{});const o=context.createOscillator(),v=context.createGain();o.connect(v);v.connect(context.destination);o.type='sine';o.frequency.setValueAtTime(freq,context.currentTime);o.frequency.exponentialRampToValueAtTime(freq*1.3,context.currentTime+.10);v.gain.setValueAtTime(.035,context.currentTime);v.gain.exponentialRampToValueAtTime(.001,context.currentTime+.13);o.start();o.stop(context.currentTime+.14);}catch(e){/* Sound is optional. */}}
function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3200);}
function stopInput(){g.keys.clear();g.joy.x=g.joy.y=0;$('knob').style.transform='translate(0px,0px)';g.moving=false;}
function show(html,mode){focusBefore=document.activeElement;stopInput();g.mode=mode;sheet.innerHTML=html;veil.classList.add('open');sheet.scrollTop=0;const x=sheet.querySelector('[data-close]');if(x)x.onclick=close;setTimeout(()=>sheet.querySelector('button')?.focus({preventScroll:true}),0);}
function close(){veil.classList.remove('open');g.mode=g.active?'play':'home';stopInput();if(focusBefore&&focusBefore.isConnected)focusBefore.focus({preventScroll:true});updateHud();}
function head(k,title,closable=true){return `<div class="sheet-head"><div><div class="eyebrow">${k}</div><h2>${title}</h2></div>${closable?'<button class="close" data-close aria-label="Закрыть">×</button>':''}</div>`;}
function effect(p,text){g.effects.push({x:p.x,y:p.y,text,born:performance.now()/1000});}
function saveSession(){if(!g.active)return;progress.session={level:g.level,player:{...g.player},items:g.world.items.map(t=>({state:t.state,order:t.order||0})),artifact:g.world.artifact.status,elapsed:g.elapsed,distance:g.distance,errors:g.errors,order:g.order};store();}
function home(){saveSession();close();g.active=false;g.mode='home';g.route=[];g.goal=null;stopInput();$('app').dataset.screen='home';const s=progress.session,idx=s?s.level:Math.max(0,progress.records.findIndex(r=>!r));$('homeKicker').textContent=s?'ТВОЙ МАРШРУТ СОХРАНЕН':'СЛЕДУЮЩАЯ ВЫЛАЗКА';$('homeTitle').textContent=`0${idx+1} / ${C.levels[idx].name}`;$('homeMeta').textContent=s?'Продолжи с того места, где остановился.':'3 зоны · сбор и сортировка · один артефакт';$('playBtn').innerHTML=`${s?'Продолжить прогулку':'На маршрут'} <span>↗</span>`;}
function newGame(level,resume=false){
 const saved=resume?progress.session:null;g.level=level;g.world=C.buildWorld(level);g.player={x:480,y:1250,facing:1};g.elapsed=0;g.distance=0;g.errors=0;g.order=0;g.effects=[];g.route=[];g.goal=null;g.active=true;g.stuck=0;
 if(saved&&saved.level===level&&Array.isArray(saved.items)&&saved.items.length===g.world.items.length){g.world.items.forEach((t,i)=>{const v=saved.items[i];t.state=[0,1,2].includes(v?.state)?v.state:0;t.order=Number.isFinite(v?.order)?v.order:0;});if(saved.player&&g.world.walkable(saved.player.x,saved.player.y))g.player={...saved.player};g.world.artifact.status=[0,1,2,3].includes(saved.artifact)?saved.artifact:0;for(let name of ['elapsed','distance','errors','order'])if(Number.isFinite(saved[name])&&saved[name]>=0)g[name]=saved[name];if(g.bag.length>g.world.def.cap)g.bag.slice(g.world.def.cap).forEach(t=>t.state=0);}
 $('app').dataset.screen='play';$('levelName').textContent=g.world.def.name;g.mode='play';close();recenter(true);updateHud();saveSession();tone(480);
 if(saved){toast('Маршрут восстановлен. Продолжай прогулку.');return;}
 const d=g.world.def;
 show(head(`МАРШРУТ 0${level+1} / БРИФИНГ`,d.name,false)+`<p>${d.story}</p><div class="steps"><div class="step"><b>↗</b><div><strong>Ходи и собирай</strong><small>Коснись мусора — герой подойдет и подберет. Или используй джойстик и кнопку «Собрать».</small></div></div><div class="step"><b>♻</b><div><strong>Возвращайся к сортировке</strong><small>В мешке ${d.cap} мест. Кнопка «К базе» прокладывает путь; там выбирай фракцию для каждой находки.</small></div></div><div class="step"><b>◇</b><div><strong>Найди особую вещь</strong><small>Очисти дальнюю зону: под мусором скрывается артефакт. Принеси его на базу.</small></div></div></div><p>Нет таймера на вылет. Можно спокойно гулять, а потом улучшить точность и время.</p><button class="primary" id="begin">Пойдем <span>↗</span></button>`,'intro');$('begin').onclick=()=>{close();toast('Коснись находки на поляне — и отправляйся к ней.');};
}
function chooseLevel(level){if(progress.session){show(head('НОВАЯ ПРОГУЛКА','Сменить маршрут?')+'<p>Сохраненная незавершенная прогулка будет заменена. Звезды и коллекция останутся.</p><button class="primary" id="replace">Начать этот маршрут <span>↗</span></button><button class="secondary full" id="keep">Продолжить сохраненный</button>','confirm');$('replace').onclick=()=>newGame(level);$('keep').onclick=()=>newGame(progress.session.level,true);}else newGame(level);}
function levels(){show(head('ТРИ КОРОТКИЕ ИСТОРИИ','Выбери маршрут')+C.levels.map((d,i)=>{const unlocked=i===0||!!progress.records[i-1],r=progress.records[i];return `<button class="location" data-level="${i}" ${unlocked?'':'disabled'}><span class="num">0${i+1}</span><span><strong>${d.name}</strong><small>${unlocked?`${d.count} находок · ${d.cap} мест в мешке`:'Сначала заверши предыдущий маршрут'}</small>${r?`<small>Рекорд: ${timeText(r.time)} · ${r.accuracy}% точности</small>`:''}</span><span class="stars">${unlocked?(r?'★'.repeat(r.stars):'↗'):'⌑'}</span></button>`;}).join('')+'<p>Каждый маршрут можно пройти заново. На второй локации мешок становится больше.</p>','levels');sheet.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>chooseLevel(Number(b.dataset.level)));}
function collection(){show(head('МУЗЕЙ СЛУЧАЙНЫХ НАХОДОК','Твои артефакты')+C.levels.map((d,i)=>{const own=progress.collection.includes(i);return `<div class="artifact-card"><div class="art-icon">${own?d.icon:'?'}</div><div><h3>${own?d.artifact:'Еще не найдено'}</h3><p>${own?d.artifactStory:`Маршрут 0${i+1}: ${d.name}`}</p></div></div>`;}).join('')+'<p>Находки попадают в коллекцию, когда ты приносишь их на базу.</p>','collection');}
function nearest(){
 const w=g.world,p=g.player;let closest=null,dist=70;
 if(w.artifact.status===1&&C.dist(w.artifact,p)<65)return{type:'artifact',obj:w.artifact};
 for(let t of w.items)if(t.state===0&&C.dist(p,t)<dist){dist=C.dist(p,t);closest={type:'item',obj:t};}
 if(closest)return closest;if(C.dist(p,w.base)<94)return{type:'base',obj:w.base};return null;
}g.nearest=nearest;
function updateHud(){if(!g.active)return;const w=g.world,bag=g.bag.length,cleared=w.zones.filter(z=>w.items.filter(t=>t.zone===z.id&&t.state>0).length===z.count).length,remaining=w.items.filter(t=>t.state===0).length;
 let next=w.zones.find(z=>w.items.some(t=>t.zone===z.id&&t.state===0)),text='',kicker='ЗАДАНИЕ КООРДИНАТОРА';
 if(bag>=w.def.cap){text='Мешок полон. Вернись на базу.';kicker='ПОРА СОРТИРОВАТЬ';}
 else if(next){text=`Очисти: ${next.name.toLowerCase()}`;kicker=`ЗОНА 0${next.id+1} / ${w.items.filter(t=>t.zone===next.id&&t.state>0).length} ИЗ ${next.count}`;}
 else if(w.artifact.status<2){text='Найди артефакт в дальней зоне.';kicker='ПОД МУСОРОМ БЫЛ СЮРПРИЗ';}
 else if(bag||w.artifact.status===2){text='Верни находки на базу.';kicker='ФИНИШ УЖЕ БЛИЗКО';}
 else text='Все готово. Зайди на базу.';
 $('questKicker').textContent=kicker;$('questText').textContent=text;$('questSub').textContent=`Чисто ${cleared}/3 зон · сдано ${g.sorted}/${w.def.count} · ${timeText(g.elapsed)}`;$('progressFill').style.width=`${(w.def.count-remaining)/w.def.count*100}%`;$('bagCount').textContent=`${bag} / ${w.def.cap}`;
 const n=nearest(),a=$('action');a.disabled=!n;let label='Подойди ближе',icon='↓';if(n?.type==='item'){label=bag>=w.def.cap?'Мешок полон':'Собрать';icon=bag>=w.def.cap?'!':'↓';}if(n?.type==='artifact'){label='Артефакт';icon='◇';}if(n?.type==='base'){label=bag?'Сортировать':w.artifact.status===2?'Передать':'База';icon='♻';}a.querySelector('span').textContent=label;a.querySelector('b').textContent=icon;
 const rh=$('routeHint');if(g.route.length){rh.style.display='block';rh.textContent=g.goal?.label||'Идем по маршруту…';}else rh.style.display='none';
}
function go(p,type='point',obj=null,label='Идем по маршруту…'){
 if(!g.active)return;stopInput();g.route=C.route(g.world,g.player,p);g.goal={type,id:obj?.id,label};if(!g.route.length){g.goal=null;toast('Здесь не пройти. Выбери точку на тропе.');return;}g.stuck=0;updateHud();
}
function toBase(){if(!g.active)return;close();if(C.dist(g.player,g.world.base)<94){atBase();return;}go(g.world.base,'base',null,'↙ Возвращаемся к пункту сортировки');}
function revealArtifact(){const a=g.world.artifact;if(a.status===0&&g.world.items.filter(t=>t.zone===2&&t.state>0).length>=Math.ceil(g.world.zones[2].count/2)){a.status=1;toast('Под мусором что-то блестит! На карте появилась ✦.');tone(920);}}
function pickup(t){if(t.state!==0)return false;if(g.bag.length>=g.world.def.cap){toast('Мешок полон. Нажми «К базе», чтобы сдать находки.');tone(180);return false;}t.state=1;t.order=++g.order;effect(t);effect(t,'+1 в мешок');tone(480+t.kind*80);revealArtifact();const z=g.world.zones[t.zone];if(g.world.items.filter(t=>t.zone===z.id&&t.state>0).length===z.count)toast(`✓ ${z.name}: мусора больше нет.`);if(g.bag.length===g.world.def.cap)toast('Мешок полон. Пора на пункт сортировки.');saveSession();updateHud();return true;}
function foundArtifact(){const a=g.world.artifact;if(a.status!==1)return;a.status=2;tone(1100);effect(a,'Артефакт!');saveSession();show(head('НЕОБЫЧНАЯ НАХОДКА',g.world.def.artifact)+`<div class="artifact-card"><div class="art-icon">${g.world.def.icon}</div><div><h3>Это не просто мусор</h3><p>${g.world.def.artifactStory}</p></div></div><p>Находка хранится отдельно и не занимает место в мешке. Принеси ее на базу — она останется в твоей коллекции.</p><button class="primary" id="artifactOK">Забрать с собой <span>◇</span></button>`,'artifact');$('artifactOK').onclick=close;}
function interact(target=nearest()){if(!g.active||!target)return;if(target.type==='item'&&C.dist(g.player,target.obj)<74)pickup(target.obj);if(target.type==='artifact'&&C.dist(g.player,target.obj)<74)foundArtifact();if(target.type==='base'&&C.dist(g.player,g.world.base)<100)atBase();}
function atBase(){g.route=[];g.goal=null;const a=g.world.artifact;if(a.status===2){a.status=3;if(!progress.collection.includes(g.level))progress.collection.push(g.level);toast('Артефакт передан и добавлен в коллекцию.');saveSession();}if(g.sorted===g.world.def.count&&a.status===3){finish();return;}if(g.bag.length){sorting();return;}show(head('ПУНКТ СОРТИРОВКИ','Мешок пока пуст')+`<p>${a.status===3?'Артефакт уже в коллекции. Осталось сдать весь мусор.':'Собирай находки в мешок и приноси сюда. Для каждого предмета нужно выбрать свою фракцию.'}</p><div class="bins">${C.kinds.map(k=>`<div class="bin" style="--c:${k.color}"><i>${k.symbol}</i>${k.name}</div>`).join('')}</div><p>Правила сортировки в игре упрощены. В жизни уточняй требования своего пункта приема.</p><button class="primary" id="leaveBase">Вернуться на маршрут <span>↗</span></button>`,'base');$('leaveBase').onclick=close;}
function sorting(message='',wrong=false){if(!g.active)return;const t=g.bag[0];if(!t){if(g.sorted===g.world.def.count&&g.world.artifact.status===3){finish();return;}show(head('ПУНКТ СОРТИРОВКИ','Мешок снова пуст')+`<p>Сдано ${g.sorted} из ${g.world.def.count} находок. ${g.world.items.some(i=>!i.state)?'Можно возвращаться за следующей партией.':'Осталось найти артефакт и принести его на базу.'}</p><button class="primary" id="continueRoute">Продолжить маршрут <span>↗</span></button>`,'base');$('continueRoute').onclick=close;return;}
 const k=C.kinds[t.kind];show(head(`НА БАЗЕ / В МЕШКЕ ${g.bag.length}`,'Куда эту находку?')+`<div class="sort-item">${C.itemSvg(t.kind)}<h3>${k.item}</h3><p>Выбери подходящий контейнер</p></div><div class="bins">${C.kinds.map((v,i)=>`<button class="bin" style="--c:${v.color}" data-sort="${i}" aria-label="${v.name}"><i>${v.symbol}</i>${v.name}</button>`).join('')}</div><p class="sort-help ${wrong?'error':''}" role="status">${message||'Ошибку можно исправить. Найденные вещи не пропадут.'}</p><p style="font-size:10px">Игровые правила упрощены. В реальности проверяй требования местного пункта приема.</p>`,'sort');sheet.querySelectorAll('[data-sort]').forEach(b=>b.onclick=()=>sortInto(Number(b.dataset.sort)));
}
function sortInto(kind){if(!g.active||g.mode!=='sort'||C.dist(g.player,g.world.base)>110)return false;const t=g.bag[0];if(!t)return false;if(kind!==t.kind){g.errors++;tone(170);saveSession();sorting(`Попробуй еще раз. ${C.kinds[t.kind].hint}`,true);updateHud();return false;}t.state=2;tone(620);effect(g.world.base,'✓ '+C.kinds[kind].name);saveSession();updateHud();sorting('✓ Верно. Следующая находка!');return true;}
function inventory(){show(head('ТВОИ НАХОДКИ',`В мешке: ${g.bag.length} / ${g.world.def.cap}`)+`<div class="inventory">${g.bag.map(t=>`<span>${C.kinds[t.kind].item}</span>`).join('')||'<p>Пока пусто. Подбирай мусор на карте.</p>'}</div><p>${g.world.artifact.status===2?'◇ Артефакт с собой. Принеси его на базу.':g.world.artifact.status===3?'◇ Артефакт уже передан в коллекцию.':'Артефакт не занимает место в мешке.'}</p><p>Чтобы отсортировать находки, нужно вернуться к контейнерам. Кнопка ниже проложит путь.</p><button class="primary" id="bagToBase">К пункту сортировки <span>↙</span></button>`,'bag');$('bagToBase').onclick=toBase;}
function map(){const w=g.world;show(head('ВЫБЕРИ СВОЙ МАРШРУТ','Карта и задания')+`<canvas class="mapcanvas" id="bigMap" width="620" height="620" aria-label="Карта. Коснись точки, чтобы проложить путь."></canvas><p class="map-legend">● Ты &nbsp; · Светлые точки — мусор &nbsp; · ✦ Артефакт &nbsp; · ⌂ База</p>${w.zones.map(z=>{const c=w.items.filter(t=>t.zone===z.id&&t.state>0).length;return `<button class="zone-btn" data-zone="${z.id}"><span>${c===z.count?'✓':'0'+(z.id+1)} ${z.name}</span><small>${c}/${z.count} собрано ↗</small></button>`;}).join('')}<button class="zone-btn" id="artifactMap"><span>◇ ${w.def.artifact}</span><small>${['Скрыт под мусором','Найден на карте ↗','С собой','В коллекции'][w.artifact.status]}</small></button><button class="primary" id="mapBase">К базе · сдано ${g.sorted}/${w.def.count} <span>↙</span></button><p style="font-size:10px">Коснись зоны или точки на карте. Белый пунктир — твой путь. Пока карта открыта, прогулка на паузе.</p>`,'map');const mc=$('bigMap');let box=mc.getBoundingClientRect();mc.width=Math.round(box.width*2);mc.height=Math.round(box.height*2);let tr=C.drawMap(g,mc,true);mc.onclick=e=>{const r=mc.getBoundingClientRect(),x=((e.clientX-r.left)*mc.width/r.width-tr.x)/tr.scale,y=((e.clientY-r.top)*mc.height/r.height-tr.y)/tr.scale;close();go({x,y});};sheet.querySelectorAll('[data-zone]').forEach(b=>b.onclick=()=>{const z=w.zones[Number(b.dataset.zone)];close();go(z,'point',null,'↗ '+z.name);});$('mapBase').onclick=toBase;$('artifactMap').onclick=()=>{if(w.artifact.status===1){close();go(w.artifact,'artifact',null,'◇ Идем к артефакту');}else if(w.artifact.status===2)toBase();else $('artifactMap').querySelector('small').textContent=w.artifact.status===0?'Очисти дальнюю зону':'Уже в коллекции ✓';};}
function pause(){if(!g.active)return;saveSession();show(head('МОЖНО ВЫДОХНУТЬ','Прогулка на паузе',false)+`<p>${g.world.def.name} · ${timeText(g.elapsed)}<br>Сдано ${g.sorted}/${g.world.def.count}. Все находки сохранены на этом устройстве.</p><div class="sound"><span>Короткие звуки действий</span><button class="secondary" id="soundToggle">${progress.sound?'Включены':'Выключены'}</button></div><button class="primary" id="resume">Продолжить <span>↗</span></button><button class="secondary full" id="exit">Сохранить и в меню</button><p style="font-size:11px">На компьютере: WASD / стрелки — ходить, пробел — собрать, M — карта, B — к базе, Esc — пауза. На телефоне: джойстик или касания карты.</p>`,'pause');$('soundToggle').onclick=()=>{progress.sound=!progress.sound;store();$('soundToggle').textContent=progress.sound?'Включены':'Выключены';};$('resume').onclick=close;$('exit').onclick=home;}
function finish(){
 if(!g.active||g.sorted!==g.world.def.count||g.world.artifact.status!==3)return;const a=accuracy(),fast=g.elapsed<=g.world.def.target,stars=1+(a>=.9?1:0)+(fast?1:0),r={stars,time:Math.round(g.elapsed),accuracy:Math.round(a*100),distance:Math.round(g.distance/16)},old=progress.records[g.level];if(!old||stars>old.stars||stars===old.stars&&r.time<old.time)progress.records[g.level]=r;
 progress.session=null;g.active=false;g.route=[];g.goal=null;store();tone(980);const unlocked=g.level<2;
 show(head('МАРШРУТ ЗАВЕРШЕН','После тебя — чисто.',false)+`<div class="result-stars">${'★'.repeat(stars)}<span style="color:#cad3bd">${'☆'.repeat(3-stars)}</span></div><div class="result-grid"><div><b>${g.world.def.count}</b><span>НАХОДОК СДАНО</span></div><div><b>${Math.round(a*100)}%</b><span>ТОЧНОСТЬ</span></div><div><b>${timeText(g.elapsed)}</b><span>ВРЕМЯ</span></div></div><p class="star-rule">✓ Убраны 3 зоны, все отсортировано, артефакт спасен.</p><p class="star-rule">${a>=.9?'✓':'○'} Звезда за точность: не менее 90%.</p><p class="star-rule">${fast?'✓':'○'} Звезда за маршрут: не дольше ${timeText(g.world.def.target)}.</p><div class="artifact-card"><div class="art-icon">${g.world.def.icon}</div><div><h3>${g.world.def.artifact}</h3><p>В твоей коллекции. Пройдено ${r.distance} игровых метров.</p></div></div><p>${unlocked?(g.level===0?'Открыта лесная тропа. Теперь в мешке 10 мест.':'Открыт маршрут «После пикника».'):'Все три маршрута пройдены! Возвращайся за тремя звездами и более коротким путем.'}</p><button class="primary" id="next">${unlocked?'Следующий маршрут':'Еще одна прогулка'} <span>↗</span></button><div class="home-links"><button class="secondary" id="replay">Повторить</button><button class="secondary" id="resultHome">В меню</button></div>`,'result');$('next').onclick=()=>{if(unlocked)newGame(g.level+1);else{home();levels();}};$('replay').onclick=()=>newGame(g.level);$('resultHome').onclick=home;
}
function recenter(instant=false){const maxX=Math.max(0,C.W-g.viewW/g.scale),maxY=Math.max(0,C.H-g.viewH/g.scale),x=Math.max(0,Math.min(maxX,g.player.x-g.viewW/g.scale*.5)),y=Math.max(0,Math.min(maxY,g.player.y-g.viewH/g.scale*.55));g.camera.x+=(x-g.camera.x)*(instant?1:.13);g.camera.y+=(y-g.camera.y)*(instant?1:.13);}
function update(dt){
 if(g.active&&(g.mode==='play'||g.mode==='sort'))g.elapsed+=dt;
 g.moving=false;if(g.active&&g.mode==='play'){
  let x=g.joy.x+(g.keys.has('ArrowRight')||g.keys.has('d')?1:0)-(g.keys.has('ArrowLeft')||g.keys.has('a')?1:0),y=g.joy.y+(g.keys.has('ArrowDown')||g.keys.has('s')?1:0)-(g.keys.has('ArrowUp')||g.keys.has('w')?1:0);let direct=Math.hypot(x,y)>.1,amount=175*dt;
  if(direct){g.route=[];g.goal=null;}else if(g.route.length){let p=g.route[0],d=C.dist(g.player,p);if(d<3){g.route.shift();}else{x=(p.x-g.player.x)/d;y=(p.y-g.player.y)/d;amount=Math.min(amount,d);}}
  const len=Math.hypot(x,y);if(len>.05){x/=Math.max(1,len);y/=Math.max(1,len);let px=g.player.x,py=g.player.y;if(g.world.walkable(g.player.x+x*amount,g.player.y))g.player.x+=x*amount;if(g.world.walkable(g.player.x,g.player.y+y*amount))g.player.y+=y*amount;let moved=Math.hypot(g.player.x-px,g.player.y-py);g.distance+=moved;g.moving=moved>.05;if(Math.abs(x)>.1)g.player.facing=x<0?-1:1;if(g.route.length&&moved<.1){g.stuck+=dt;if(g.stuck>.8){g.route=[];g.goal=null;toast('Обойди дерево или выбери другую точку на тропе.');g.stuck=0;}}else g.stuck=0;}
  if(!g.route.length&&g.goal){const goal=g.goal;g.goal=null;if(goal.type==='item'){const t=g.world.items[goal.id];if(t&&!t.state)interact({type:'item',obj:t});}if(goal.type==='base')interact({type:'base',obj:g.world.base});if(goal.type==='artifact')interact({type:'artifact',obj:g.world.artifact});}
 }
 recenter();
}
function resize(){const r=$('stage').getBoundingClientRect();g.viewW=r.width;g.viewH=r.height;g.dpr=Math.min(window.devicePixelRatio||1,2);g.scale=Math.min(1.1,r.width/430);canvas.width=Math.round(r.width*g.dpr);canvas.height=Math.round(r.height*g.dpr);recenter(true);}
function frame(ts){const dt=lastFrame?Math.min(.06,(ts-lastFrame)/1000):0;lastFrame=ts;update(dt);C.draw(g,canvas,ts/1000);g.effects=g.effects.filter(e=>ts/1000-e.born<1);if(ts-lastUi>180){updateHud();lastUi=ts;}if(g.active&&ts-lastMini>240){C.drawMap(g,$('mini'));lastMini=ts;}if(g.active&&ts-lastSave>5000){saveSession();lastSave=ts;}requestAnimationFrame(frame);}
// All listeners are registered once. Pointer capture keeps the joystick responsive outside its circle.
let stickId=null;
function joyMove(e){const r=$('stick').getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,d=Math.hypot(dx,dy),scale=d>34?34/d:1;g.joy.x=dx*scale/34;g.joy.y=dy*scale/34;$('knob').style.transform=`translate(${dx*scale}px,${dy*scale}px)`;}
$('stick').addEventListener('pointerdown',e=>{if(g.mode!=='play')return;e.preventDefault();stickId=e.pointerId;$('stick').setPointerCapture(e.pointerId);joyMove(e);g.route=[];g.goal=null;});$('stick').addEventListener('pointermove',e=>{if(e.pointerId===stickId){e.preventDefault();joyMove(e);}});for(let name of ['pointerup','pointercancel','lostpointercapture'])$('stick').addEventListener(name,e=>{if(e.pointerId===stickId){stickId=null;g.joy.x=g.joy.y=0;$('knob').style.transform='translate(0px,0px)';}});
let press=null;canvas.addEventListener('pointerdown',e=>{if(g.mode==='play')press={x:e.clientX,y:e.clientY,id:e.pointerId};});canvas.addEventListener('pointercancel',()=>press=null);canvas.addEventListener('pointerup',e=>{if(g.mode!=='play'||!press||press.id!==e.pointerId)return;const start=press;press=null;if(Math.hypot(e.clientX-start.x,e.clientY-start.y)>15)return;const r=canvas.getBoundingClientRect(),p={x:(e.clientX-r.left)/g.scale+g.camera.x,y:(e.clientY-r.top)/g.scale+g.camera.y},w=g.world;
 if(w.artifact.status===1&&C.dist(p,w.artifact)<35){if(C.dist(g.player,w.artifact)<70)foundArtifact();else go(w.artifact,'artifact',null,'◇ Идем к артефакту');return;}
 let item=w.items.filter(t=>!t.state).sort((a,b)=>C.dist(p,a)-C.dist(p,b))[0];if(item&&C.dist(p,item)<35){if(g.bag.length>=w.def.cap){toast('Мешок полон. Сначала вернись на базу.');return;}if(C.dist(g.player,item)<70)pickup(item);else go(item,'item',item,'↓ Идем за находкой');return;}
 if(C.dist(p,w.base)<110){toBase();return;}go(p);
});
$('playBtn').onclick=()=>{const s=progress.session;newGame(s?s.level:Math.max(0,progress.records.findIndex(r=>!r)),!!s);};$('levelsBtn').onclick=levels;$('collectionBtn').onclick=collection;$('pauseBtn').onclick=pause;$('miniBtn').onclick=map;$('bagBtn').onclick=inventory;$('baseBtn').onclick=toBase;$('action').onclick=()=>{if(g.mode==='play'){g.route=[];g.goal=null;interact();}};
window.addEventListener('keydown',e=>{const key=e.key.length===1?e.key.toLowerCase():e.key;if(veil.classList.contains('open')){if(key==='Tab'){const fs=[...sheet.querySelectorAll('button:not(:disabled)')];if(fs.length){const first=fs[0],last=fs[fs.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}if(key==='Escape'&&!['intro','result'].includes(g.mode)){e.preventDefault();close();}return;}if(!g.active)return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','w','a','s','d',' '].includes(key)){e.preventDefault();if(key===' '){if(!e.repeat)interact();}else g.keys.add(key);}if(key==='Escape'){e.preventDefault();pause();}if(key==='m')map();if(key==='b')toBase();});window.addEventListener('keyup',e=>g.keys.delete(e.key.length===1?e.key.toLowerCase():e.key));window.addEventListener('blur',stopInput);document.addEventListener('visibilitychange',()=>{if(document.hidden){stopInput();if(g.active){saveSession();if(g.mode==='play'||g.mode==='sort')pause();}}});window.addEventListener('pagehide',saveSession);window.addEventListener('resize',resize);new ResizeObserver(resize).observe($('stage'));
// Test hooks are enabled only on an explicit local/QA query; normal play has no debug controls.
if(new URLSearchParams(location.search).get('test')==='1')C.test={newGame,close,update,go,pickup,interact,sortInto,atBase,map,inventory,pause,home,finish,saveSession,progress};
resize();home();requestAnimationFrame(frame);
})();
