/* Interface and persistence. State commits atomically before each visual animation. */
'use strict';
(()=>{
 const T=window.Team,M=window.TeamMap,$=id=>document.getElementById(id),KEY='clean-team-v1';
 let saved={version:1,session:null,best:null,last:null},storageWarned=false;
 try{const data=JSON.parse(localStorage.getItem(KEY));if(data?.version===1){saved.session=T.restore(data.session);if(data.best&&Number.isFinite(data.best.score))saved.best=data.best;if(data.last&&Number.isFinite(data.last.score))saved.last=data.last;}}catch(e){}
 let s=saved.session||T.make(),selected=s.node,busy=false,inGame=false,modal='',lastFocus=null,toastTimer=null,runId=0,history=[];
 const view=new M.View($('map'),()=>s,selectNode);view.fit();
 const noMotion=window.matchMedia?.('(prefers-reduced-motion: reduce)').matches;
 const esc=text=>String(text).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),5200);}
 function persist(){try{localStorage.setItem(KEY,JSON.stringify(saved));}catch(e){if(!storageWarned){storageWarned=true;toast('Браузер не разрешает сохранение. Раунд можно пройти, но после закрытия прогресс потеряется.');}}}
 function save(){if(inGame&&!s.finished){saved.session=JSON.parse(JSON.stringify(s));persist();}}
 function hide(){ $('veil').classList.remove('open');modal='';if(lastFocus?.isConnected)lastFocus.focus({preventScroll:true}); }
 function sheet(kicker,title,html,name='info',closable=true){lastFocus=document.activeElement;modal=name;$('sheet').innerHTML=`<div class="sheet-head"><div><div class="kicker">${kicker}</div><h2 id="sheetTitle">${title}</h2></div>${closable?'<button class="close" id="closeSheet" aria-label="Закрыть">×</button>':''}</div>`+html;$('veil').classList.add('open');$('sheet').scrollTop=0;if($('closeSheet'))$('closeSheet').onclick=hide;setTimeout(()=>$('sheet').querySelector('button:not(:disabled)')?.focus({preventScroll:true}),0);}
 function btn(id,text,secondary=false,disabled=false){return `<button class="${secondary?'secondary':'primary'}" id="${id}" ${disabled?'disabled':''}>${text}<span>↗</span></button>`;}
 function bind(id,fn){if($(id))$(id).onclick=fn;}
 function number(x){return Number.isFinite(x)?String(x):'∞';}
 function zoneCount(z,accepted=false){return T.piles.filter(p=>p.node===z).reduce((a,p)=>a+((accepted?s.state[p.id]===3:s.state[p.id]>0)?p.q:0),0);}
 function zoneTotal(z){return T.piles.filter(p=>p.node===z).reduce((a,p)=>a+p.q,0);}
 function reserve(state=s){return T.path(state.node,'base').cost+(T.load(state)?1:0);}
 function can(a){return !T.validate(s,a);}
 function actionRisk(a){const r=T.apply(s,a);if(!r.ok)return '';const spare=T.remaining(r.s),back=reserve(r.s);if(spare<back)return `<div class="highlight warning">После действия останется ${number(spare)} х. Возврат и сдача потребуют еще ${back}. Есть риск не успеть на финиш.</div>`;return '';}
 function hud(){
  $('clock').textContent=s.relaxed?'∞':T.remaining(s);$('clockMax').textContent=s.relaxed?'ходов':`/ ${T.LIMIT}`;$('clockLabel').textContent=s.relaxed?'СПОКОЙНАЯ ПРОГУЛКА':'ОСТАЛОСЬ ХОДОВ';$('score').textContent=T.points(s).total;
  $('goal1').textContent=(T.delivered(s,'lawn')?'✓':'01')+' Поляна · '+zoneCount('lawn')+'/10';$('goal2').textContent=(T.delivered(s,'picnic')?'✓':'02')+' Пикник · '+zoneCount('picnic')+'/9';
  const back=reserve();$('reserve').textContent=s.node==='base'?'На складе · сдача мешков занимает 1 ход':`До склада ${T.path(s.node,'base').cost} х.${T.load(s)?' + 1 х. на сдачу':''}`;$('reserve').classList.toggle('danger',T.remaining(s)<=back+2&&s.node!=='base');
  const b=s.buddy;$('buddyStatus').textContent=T.together(s)?'Рядом. Готова помочь':b.mode==='unload'?'На складе · принимает скупщик':`${b.mode==='delivery'?'Несет '+T.load(s,2)+' ед.':'Возвращается'} · рядом через ~${T.eta(s)} х.`;
  $('bagCount').textContent=`Мешки ${T.load(s)} / ${T.CAP}`;$('bagDots').innerHTML=T.bags(s).map((v,i)=>`<i style="--c:${T.kinds[i].color}" title="${T.kinds[i].name}: ${v}">${v}</i>`).join('');
  const n=T.nodes[selected],here=selected===s.node;$('locationName').textContent=n.name;$('here').textContent=here?'Ты здесь':T.path(s.node,selected).cost+' х. пути';
  $('locationDesc').textContent=T.zones.includes(selected)?`${n.goal?'Обязательный участок':'Бонусный участок'} · ${zoneCount(selected)}/${zoneTotal(selected)} собрано`:selected==='base'?'Скупщик · мешки · конкурс артефактов':n.tag.toLowerCase();
  $('mainAction').innerHTML=busy?'Команда выполняет действие…':here?`Осмотреть${selected==='base'?' склад':' участок'} <span>↗</span>`:`Идти сюда · ${T.path(s.node,selected).cost} х. <span>↗</span>`;$('mainAction').disabled=busy;$('app').classList.toggle('busy',busy);
  $('mapHint').textContent=busy?'Действие выполняется. Карта остается подвижной.':'Тяни карту · щипок — масштаб · касание — участок';view.selected=selected;
 }
 function home(){save();hide();inGame=false;view.home=true;$('app').dataset.screen='home';view.fit();$('start').innerHTML=saved.session?'Продолжить мой маршрут <span>↗</span>':`Начать раунд · ${T.LIMIT} ходов <span>↗</span>`;}
 function start(relaxed=false,resume=false){
  s=resume&&saved.session?T.restore(saved.session):T.make(relaxed);if(!s)s=T.make(relaxed);s.finished=false;selected=s.node;inGame=true;history=[];hide();view.home=false;view.selected=selected;$('app').dataset.screen='game';view.fit();hud();save();
  if(resume){toast('Маршрут восстановлен. Мешки и задание Лены сохранены.');return;}
  sheet('БРИФИНГ / ПОСЛЕ ПРАЗДНИКА','Сегодня ты — капитан.',`<p>Вчера здесь был районный праздник. Координатор просит убрать <b>Большую поляну</b> и <b>Место пикника</b>. Старая сцена — дополнительная задача.</p><div class="quote">Лена: «Могу возить мешки на склад, пока ты работаешь. Но крупную стойку у сцены придется убирать вместе».</div><div class="steps"><div class="step"><i>↗</i><div><b>Сначала выбери путь</b><small>Тяни карту и приближай двумя пальцами. Коснись участка: перед переходом увидишь цену в ходах.</small></div></div><div class="step"><i>♻</i><div><b>Сортируй прямо на месте</b><small>Для партии мусора выбери мешок. Вместимость общая: 12 единиц. Баллы начисляются после сдачи.</small></div></div><div class="step"><i>◷</i><div><b>${s.relaxed?'Гуляй без ограничения':'На раунд — 48 игровых ходов'}</b><small>Часы не тикают. Ходы уходят только на подтвержденные действия. Обзор карты и чтение — бесплатно.</small></div></div></div><div class="highlight">Для зачета: очистить <b>два обязательных участка</b>, сдать собранное и вернуться на склад. Фото, сцена и кубок — бонусы, а не условия выхода.</div>${btn('begin','Выбрать маршрут')}`,'brief',false);bind('begin',()=>{hide();view.fit();toast('Начни с поляны слева или пикника справа. Решение за тобой.');});
 }
 function askStart(relaxed){if(!saved.session){start(relaxed);return;}sheet('НОВЫЙ РАУНД','Начать заново?',`<p>Незавершенный командный маршрут будет заменен. Личный рекорд и две предыдущие игры останутся без изменений.</p>${btn('replace','Начать '+(relaxed?'прогулку':'новый раунд'))}${btn('resumeOld','Продолжить сохраненный',true)}`);bind('replace',()=>start(relaxed));bind('resumeOld',()=>start(false,true));}
 function selectNode(id){if(!inGame||busy||!T.nodes[id])return;selected=id;view.selected=id;hud();if(id===s.node)inspect();}
 function travel(){if(selected===s.node){inspect();return;}const to=selected,a={type:'move',to},route=T.path(s.node,to);sheet('ПЛАНИРОВАНИЕ / ВРЕМЯ СТОИТ',T.nodes[to].name,`<p>${route.nodes.map(n=>T.nodes[n].name).join(' → ')}</p><div class="route-cost"><div><small>СТОИМОСТЬ ПЕРЕХОДА</small><strong>${route.cost}</strong><span> х.</span></div><div><small>ОСТАНЕТСЯ</small><strong>${number(T.remaining(s)-route.cost)}</strong></div></div><p>${T.zones.includes(to)?`${zoneTotal(to)-zoneCount(to)} единиц мусора на участке. ${to==='stage'?'Стойка требует двух участников. На стенде есть история кубка.':'Нужно собрать и сдать все находки этого участка.'}`:'Можно остановиться здесь или выбрать следующий участок. Цена пути учитывает все развилки.'}</p>${!T.together(s)?`<p>Пока ты идешь, Лена продолжает доставку и возвращение.</p>`:''}${actionRisk(a)}${btn('confirmMove','Идти · '+route.cost+' х.',false,!can(a))}<p class="fine">Стоимость видна заранее. Переходы анимированы, но реальное ожидание не расходует ходы.</p>`,'travel');bind('confirmMove',()=>run(a));}
 function inspect(){if(busy||!inGame)return;selected=s.node;hud();if(s.node==='base'){base();return;}const z=s.node,n=T.nodes[z],remaining=T.piles.filter(p=>p.node===z&&!s.state[p.id]);
  let html='';
  if(T.zones.includes(z)){
   html+=`<p>${n.goal?'Задание координатора':'Дополнительная уборка'} · собрано ${zoneCount(z)}/${zoneTotal(z)}. В твоих мешках ${T.load(s)}/${T.CAP} мест.</p>`;
   html+=remaining.map(p=>`<button class="pile" data-pile="${p.id}"><span class="pile-icon">${p.heavy?'⚒':'♻'}</span><span><b>${p.name}</b><small>${p.q} ед. · ${p.heavy?'нужны оба участника':'одна партия'}${p.heavy&&!T.together(s)?' · Лена в пути':''}</small></span><span class="cost">${p.heavy?2:1} х. ↗</span></button>`).join('');
   if(!remaining.length)html+='<div class="highlight">✓ На участке чисто. <b>Не забудь сдать мешки:</b> сбор и приемка — разные этапы.</div>';
   if(T.clear(s,z)&&!s.photos.includes(z))html+=btn('takePhoto','Фото «после» · 1 х. / +8 баллов',true,!can({type:'photo'}));
   if(s.photos.includes(z))html+=btn('seePhoto','Посмотреть фото «до / после»',true);
   if(z==='picnic'&&T.clear(s,z)&&s.artifact===0)html+=`<div class="highlight">✦ Под последней партией оказался старый кубок. На нем надпись: «Команда двора · 2001».</div>${btn('takeArtifact','Забрать кубок · 1 х.',false,!can({type:'artifact'}))}`;
   if(z==='stage')html+=s.story?'<p>✓ История со стенда записана. На конкурсе артефактов это даст дополнительные 10 баллов.</p>':btn('readStory','Прочесть стенд · 1 х.',true,!can({type:'story'}));
  }else html+=`<p>Это развилка. Дальше можно пройти к другому участку — выбирай ближайшую тропу или закрой окно и посмотри весь парк.</p>`;
  html+=`<div class="split">${btn('nodeBuddy','Лена и мешки',true)}${btn('nodeMap','Посмотреть карту',true)}</div>`;
  if(!T.zones.includes(z))html+=T.edges.filter(e=>e[0]===z||e[1]===z).map(e=>{const to=e[0]===z?e[1]:e[0];return `<button class="pile" data-dest="${to}"><span><b>${T.nodes[to].name}</b><small>Прямая тропа</small></span><span class="cost">${e[2]} х. ↗</span></button>`;}).join('');
  sheet(n.tag,n.name,html,'node');$('sheet').querySelectorAll('[data-pile]').forEach(b=>b.onclick=()=>collect(Number(b.dataset.pile)));$('sheet').querySelectorAll('[data-dest]').forEach(b=>b.onclick=()=>{selected=b.dataset.dest;hud();travel();});
  bind('takePhoto',()=>run({type:'photo'},()=>photos(z)));bind('seePhoto',()=>photos(z));bind('takeArtifact',()=>run({type:'artifact'},artifactStory));bind('readStory',()=>run({type:'story'},poster));bind('nodeBuddy',buddy);bind('nodeMap',()=>{hide();view.fit();});
 }
 function collect(id){const p=T.piles[id];if(!p||s.node!==p.node)return;const full=T.load(s)+p.q>T.CAP,need=p.heavy&&!T.together(s);sheet('РАЗДЕЛЬНЫЙ СБОР / НА ТЕРРИТОРИИ','В какой мешок?',`<div class="object-preview"><span class="object">${['♳','▤','◇','▱','▰'][p.kind]}</span><h3>${p.name}</h3><small>${p.q} единиц · ${p.heavy?'2 хода и оба участника':'1 ход на всю партию'}</small></div>${full?'<div class="highlight warning">Недостаточно места. Передай мешки Лене или отнеси на склад.</div>':''}${need?`<div class="highlight warning">Лена сейчас в пути. До встречи примерно ${T.eta(s)} х. Можно собирать обычный мусор, читать стенд или подождать.</div>`:''}<div class="bins">${T.kinds.map((k,i)=>`<button class="bin" data-kind="${i}" style="--c:${k.color}" ${full||need||T.remaining(s)<(p.heavy?2:1)?'disabled':''}><i>${k.symbol}</i>${k.name}</button>`).join('')}</div>${actionRisk({type:'collect',id,kind:p.kind})}<p class="fine">Нажатие на мешок подтверждает сбор. Ошибку можно исправить; пересортировка стоит 1 ход. Игровая схема упрощена: в жизни проверяй требования местного пункта приема.</p>${full||need?btn('collectBuddy','Поручение для Лены / ожидание',true):''}`,'collect');$('sheet').querySelectorAll('[data-kind]').forEach(b=>b.onclick=()=>{const k=Number(b.dataset.kind);run({type:'collect',id,kind:k},()=>{if(s.state[id]===0)collect(id);else inspect();});});bind('collectBuddy',buddy);}
 function buddy(){const nearby=T.together(s),a={type:'dispatch'},e=T.eta(s);sheet('ТВОЯ КОМАНДА','Лена на связи',`<div class="quote">${nearby?'«Передавай мешки — отвезу и догоню. Пока меня нет, крупные вещи не трогай: их убираем вместе».':s.buddy.mode==='delivery'?'«Несколько фракций — несколько мешков. Везу все на склад. Можешь продолжать уборку!»':'«Мешки приняты! Возвращаюсь к тебе. На карте я отмечена оранжевой точкой».'}</div><div class="highlight">${nearby?'Лена рядом.':`До встречи примерно <b>${e} ходов</b>. Путь меняется, если ты переходишь на другой участок.`}<br>У капитана: ${T.load(s)}/${T.CAP}. У Лены: ${T.load(s,2)}/${T.CAP} единиц.</div>${nearby&&s.node!=='base'?`<p>Отправка занимает 1 ход. Дорога, приемка на складе и возвращение идут параллельно твоим действиям.</p>${actionRisk(a)}${btn('dispatch','Передать мешки · 1 х.',false,!can(a))}`:nearby?'<p>Вы на складе. Здесь капитан может сдать мешки сам за 1 ход.</p>':'<p>Чтение и обзор карты не продвигают доставку. Работай на участке или потрать ходы ожидания.</p>'}<h3>Подождать напарницу</h3><div class="wait-row">${[1,2,4].map(n=>`<button class="secondary" data-wait="${n}" ${!can({type:'wait',n})||nearby?'disabled':''}>${n} х.</button>`).join('')}</div>${btn('backWork','Вернуться к участку',true)}<p class="fine">Если движешься во время доставки, Лена после сдачи идет к твоему новому местоположению.</p>`,'buddy');bind('dispatch',()=>run(a));$('sheet').querySelectorAll('[data-wait]').forEach(b=>b.onclick=()=>run({type:'wait',n:Number(b.dataset.wait)},buddy));bind('backWork',inspect);}
 function inventory(){const amounts=T.bags(s);sheet('КАПИТАН / РАЗДЕЛЬНЫЕ МЕШКИ',`${T.load(s)} из ${T.CAP} мест`,T.kinds.map((k,i)=>`<div class="score-row"><span>${k.symbol} ${k.name}</span><b>${amounts[i]}</b></div>`).join('')+`<p>Вместимость общая для всех фракций. Каждый предмет занимает одно место; крупная стойка — четыре.</p><p>Кубок: ${['еще не найден','','с собой, места не занимает','на конкурсе артефактов'][s.artifact]}.</p>${btn('bagCourier','Передать Лене',false,!can({type:'dispatch'}))}${btn('bagBase','Спланировать возврат на склад',true)}`,'bag');bind('bagCourier',buddy);bind('bagBase',()=>{selected='base';hud();if(s.node==='base')base();else travel();});}
 function base(){const main=T.delivered(s,'lawn')&&T.delivered(s,'picnic');sheet('СКУПЩИК / ПРИЕМКА И ФИНИШ','Добро пожаловать на склад',`<p>Сдаются уже разделенные фракции. В твоих мешках <b>${T.load(s)}</b> ед.${T.load(s,2)?` Лена везет еще ${T.load(s,2)}.`:''}</p>${btn('deposit','Сдать мешки · 1 х.',false,!can({type:'deposit'}))}<div class="rule-table">${T.kinds.map(k=>`<div>${k.name}<b>+${k.rate}</b>за 1 ед.</div>`).join('')}</div><p class="fine">Тарифы придуманы для этого прототипа и не являются официальной таблицей баллов Чистых Игр.</p>${s.artifact===2?btn('present','Представить артефакт · 1 х.',true,!can({type:'present'})):s.artifact===3?`<div class="highlight">✦ «${esc(s.title)}» участвует в конкурсе. ${s.story?'История кубка восстановлена.':'Бонус за историю пока не получен.'}</div>`:''}<div class="highlight ${main?'':'warning'}">${main?'✓ Обязательные участки убраны, все их находки приняты. Можно финишировать или отправиться за бонусами.':`Для зачета осталось сдать: поляна ${zoneCount('lawn',true)}/10, пикник ${zoneCount('picnic',true)}/9. Можно завершить и неполный раунд — результат будет показан.`}</div>${btn('finishAsk',main?'Финишировать командой':'Завершить неполный раунд',true)}${btn('warehouseMap','Вернуться на карту',true)}`,'base');bind('deposit',()=>run({type:'deposit'},base));bind('present',presentation);bind('finishAsk',()=>confirmFinish(false));bind('warehouseMap',()=>{hide();view.fit();});}
 function confirmFinish(anywhere=false){const q=T.points(s),undelivered=T.load(s)+T.load(s,2);sheet('ФИНИШ КОМАНДЫ',q.success?'Зафиксировать результат?':'Закончить эту попытку?',`<p>${q.success?'Основные задания выполнены. Бонусные задания необязательны.':'Нужно сдать находки двух обязательных участков и вернуться на склад. Маршрут пока не зачтен. Ты увидишь промежуточный результат и сможешь попробовать другой план.'}</p>${undelivered?`<div class="highlight warning">${undelivered} единиц еще не приняты на складе и не принесут баллов. ${T.load(s,2)?'Лена продолжает работу только пока ты тратишь ходы.':''}</div>`:''}<div class="route-cost"><span>Результат сейчас</span><strong>${q.total}</strong></div>${btn('finishNow','Подтвердить финиш')}${btn('keepPlaying','Продолжить уборку',true)}`,'finish');bind('finishNow',()=>run({type:anywhere?'end':'finish'}));bind('keepPlaying',hide);}
 function tasks(){sheet('ПЛАН КОМАНДЫ','Два задания. Твой путь.',`<p>Для зачета обязательные находки должны попасть на склад. Сцена, фотографии и кубок дают дополнительные баллы.</p>`+T.zones.map(z=>`<div class="goal-card"><b>${T.delivered(s,z)?'✓':T.nodes[z].icon} ${T.nodes[z].name} · ${T.nodes[z].goal?'основное':'бонус'}</b><small>Собрано ${zoneCount(z)}/${zoneTotal(z)} · принято ${zoneCount(z,true)}/${zoneTotal(z)}<br>${z==='stage'?'Крупная стойка — работа для двоих. На стенде — история кубка.':'Убери все партии на участке, затем сдай мешки.'}</small><button class="secondary" data-task="${z}">${s.node===z?'Осмотреть':'Выбрать на карте'} <span>↗</span></button></div>`).join('')+`<div class="goal-card"><b>▣ Фото «до / после»</b><small>${s.photos.length}/3 снимков · +8 за каждый. Кнопка появляется после полной уборки участка.</small></div><div class="goal-card"><b>✦ Артефакт с историей</b><small>${s.artifact===3?'Кубок представлен на финише.':s.artifact===2?'Кубок с собой. Принеси его на финиш.':'Ищи кубок после уборки места пикника.'} ${s.story?'История со стенда уже известна.':'История — на стенде у старой сцены.'}</small></div>${btn('tasksBase','Выбрать склад и финиш',true)}<p class="fine">За полностью сданный участок: +10. Обзор карты, окна заданий и чтение подсказок не тратят ходы.</p>`,'tasks');$('sheet').querySelectorAll('[data-task]').forEach(b=>b.onclick=()=>{hide();selected=b.dataset.task;hud();if(s.node===selected)inspect();else {view.x=T.nodes[selected].x;view.y=T.nodes[selected].y+80;view.zoom=.65;view.follow=false;}});bind('tasksBase',()=>{hide();selected='base';hud();if(s.node==='base')base();else travel();});}
 function artifactStory(){sheet('НАХОДКА / МАЛЕНЬКАЯ ИСТОРИЯ','Кубок, который забыли',`<div class="object-preview"><span class="object">♜</span><h3>«Команда двора · 2001»</h3><small>Старая надпись еще читается</small></div><p>Может быть, это награда за тот самый праздник? На стенде у старой сцены остались фотографии и подписи.</p><p>Можно сразу отнести кубок на конкурс артефактов: <b>+20 баллов</b>. Восстановленная история даст еще <b>+10</b>. Делать крюк необязательно.</p>${btn('artifactContinue','Продолжить маршрут')}`,'story');bind('artifactContinue',hide);}
 function poster(){sheet('СТЕНД У СЦЕНЫ / 2001 ГОД','За помощь после праздника',`<div class="quote">«Дворовый турнир завершился ничьей. Кубок отдали команде, которая после игры осталась помогать всем убирать площадку».</div><p>Лена улыбается: «Кажется, сегодня мы их команда-продолжение».</p><p>${s.artifact===3?'Скупщик добавит историю к представленному кубку. Бонус +10 уже учтен.':s.artifact===2?'История записана. Представь кубок на финише и получи 30 баллов вместо 20.':'История записана. Сам кубок может оказаться на месте пикника.'}</p>${btn('posterContinue','Вернуться к уборке')}`,'story');bind('posterContinue',inspect);}
 function presentation(){sheet('КОНКУРС АРТЕФАКТОВ','Как назовем находку?',`<p>Короткое выступление — 1 ход. Здесь нет единственного правильного ответа: все названия дают одинаковый бонус.</p><div class="highlight">${s.story?'Ты знаешь историю команды 2001 года. Награда за выступление: +30 баллов.':'У кубка появится вторая жизнь. Награда за выступление: +20 баллов.'}</div>${['Кубок второго шанса','Приз за волю к уборке','2001: чистая одиссея'].map((n,i)=>`<button class="pile" data-title="${i}"><span><b>${n}</b></span><span class="cost">1 х. ↗</span></button>`).join('')}`,'present');$('sheet').querySelectorAll('[data-title]').forEach(b=>b.onclick=()=>run({type:'present',choice:Number(b.dataset.title)},()=>{sheet('ВЕДУЩИЙ / КОНКУРС НАХОДОК','«'+esc(s.title)+'»',`<p>«Принимается! У этой вещи теперь есть и новая команда, и новая история».</p><div class="highlight">+${s.story?30:20} баллов за артефакт${s.story?' и восстановленную историю':''}.</div>${btn('afterPresent','Вернуться на склад')}`);bind('afterPresent',base);}));}
 function photos(z){sheet('ЧЕКИН / '+T.nodes[z].name,'Разница — в твоих руках.',`<div class="photo-pair"><figure><img alt="Участок до уборки" src="${M.region(s,z,true)}"><figcaption>ДО / СТАРТ</figcaption></figure><figure><img alt="Участок после уборки" src="${M.region(s,z,false)}"><figcaption>ПОСЛЕ / ТВОЯ КОМАНДА</figcaption></figure></div><p>Игровой снимок сохранен в этом раунде. <b>+8 баллов.</b> Камера телефона не используется.</p>${btn('photoContinue','Продолжить маршрут')}`,'photo');bind('photoContinue',hide);}
 async function run(a,after){if(busy||!inGame)return false;const r=T.apply(s,a);if(!r.ok){toast(r.error);return false;}const thisRun=++runId;history.push({turn:s.turn,type:a.type,to:a.to,id:a.id,cost:r.cost});hide();s=r.s;selected=s.node;if(s.finished){view.trace=null;busy=false;hud();finishResult();return true;}busy=true;const dur=noMotion?30:view.animate(r);save();hud();await new Promise(resolve=>setTimeout(resolve,dur));if(thisRun!==runId)return false;view.trace=null;busy=false;hud();if(s.finished){finishResult();return true;}if(r.events.length)toast(r.events.join(' '));if(after)after();return true;}
 function resultData(){const q=T.points(s),all=T.delivered(s,'stage'),stars=q.success?1+(s.photos.includes('lawn')&&s.photos.includes('picnic')?1:0)+(all&&s.artifact===3&&s.story?1:0):0;return {score:q.total,stars,success:q.success,turn:s.turn,errors:s.errors,relaxed:s.relaxed,accepted:T.piles.reduce((a,p)=>a+(s.state[p.id]===3?p.q:0),0),spent:{...s.spent},build:T.VERSION};}
 function finishResult(){const r=resultData(),q=T.points(s);saved.session=null;saved.last=r;let record=false;if(r.success&&!r.relaxed&&(!saved.best||r.score>saved.best.score||r.score===saved.best.score&&r.turn<saved.best.turn)){saved.best=r;record=true;}persist();
  sheet(s.relaxed?'ПРОГУЛКА ЗАВЕРШЕНА':s.turn>=T.LIMIT?'ФИНИШНЫЙ СИГНАЛ':'КОМАНДА НА ФИНИШЕ',r.success?'После нас — чисто.':'Есть идея для нового плана.',`<div class="stars">${'★'.repeat(r.stars)}<span style="color:#bfcbaa">${'☆'.repeat(3-r.stars)}</span></div><div class="results"><div class="result-cell"><b>${r.score}</b><span>БАЛЛОВ</span></div><div class="result-cell"><b>${r.accepted}</b><span>ПРИНЯТО ЕДИНИЦ</span></div><div class="result-cell"><b>${s.turn}</b><span>ХОДОВ ПОТРАЧЕНО</span></div></div>${record?'<div class="highlight">↗ Новый личный рекорд!</div>':''}${!r.success?`<div class="highlight warning">${!T.delivered(s,'lawn')||!T.delivered(s,'picnic')?'Не все обязательные находки приняты на складе. ':''}${s.node!=='base'?'Капитан не успел вернуться на финиш. ':''}Частичный результат показан, но маршрут пока не зачтен.</div>`:''}<div class="score-row"><span>Принятые фракции</span><b>+${q.accepted}</b></div><div class="score-row"><span>Полностью сданные участки</span><b>+${q.cleanBonus}</b></div><div class="score-row"><span>Фото «до / после»</span><b>+${q.photoBonus}</b></div><div class="score-row"><span>Артефакт и история</span><b>+${q.artifactBonus}</b></div><div class="score-row"><span>Сэкономленные ходы</span><b>+${q.efficiency}</b></div><p class="fine">★ Основные задания и возврат. ★ Фото двух обязательных участков. ★ Сцена сдана, кубок представлен с историей.</p><div class="highlight">Твой план: <b>${s.spent.walk}</b> х. переходов · <b>${s.spent.work}</b> х. работы · <b>${s.spent.wait}</b> х. ожидания. Ошибок сортировки: ${s.errors}.</div><p>${s.spent.wait>3?'Попробуй занять ожидание сбором или чтением стенда: Лена продолжает путь во время твоих действий.':T.load(s)+T.load(s,2)>0?'В следующий раз оставь ходы на сдачу мешков. Собранное приносит очки только после приемки.':'Проверь другой порядок участков и момент отправки Лены. Та же карта допускает другой план.'}</p>${btn('retry','Попробовать другой план')}${!r.success?btn('continuePractice','Доиграть без ограничения ходов',true):''}<div class="split">${btn('shareResult','Копировать результат',true)}${btn('resultHome','В меню',true)}</div><p class="fine">${s.relaxed?'Это спокойная прогулка. Соревновательный рекорд не изменяется.':'Это личный результат в этом браузере. Общего онлайн-рейтинга пока нет.'}</p>`,'result',false);
  bind('retry',()=>start(s.relaxed));bind('resultHome',home);bind('continuePractice',()=>{s.finished=false;s.relaxed=true;hide();selected=s.node;save();hud();toast('Продолжаем без лимита. Эта попытка не заменит соревновательный рекорд.');});bind('shareResult',()=>copyResult(r));
 }
 function copyResult(r){const url=location.protocol.startsWith('http')?location.origin+location.pathname:'';const text=`Чистый маршрут: Команда\n${r.score} баллов · ${r.stars}/3 звезд · ${r.turn} ходов\nПринято ${r.accepted} единиц. ${r.relaxed?'Спокойная прогулка.':'Раунд на 48 ходов.'}\n${url}`;if(navigator.clipboard?.writeText)navigator.clipboard.writeText(text).then(()=>toast(url?'Результат и ссылка скопированы.':'Результат скопирован.')).catch(()=>copyFallback(text));else copyFallback(text);}
 function copyFallback(text){sheet('РЕЗУЛЬТАТ ДЛЯ ДРУЗЕЙ','Скопируй этот текст',`<textarea class="copy" readonly id="copyText">${esc(text)}</textarea><p>Выдели текст и скопируй обычным способом.</p>`);$('copyText').select();}
 function help(){sheet('КАК УСТРОЕНА ЭТА ВЕРСИЯ','План важнее скорости.',`<div class="steps"><div class="step"><i>↗</i><div><b>Обзор карты свободный</b><small>Перетаскивай пальцем или мышью. Масштаб: два пальца, колесо или + / −. «Весь парк» показывает развилки, «К герою» возвращает камеру.</small></div></div><div class="step"><i>◷</i><div><b>Игра тратит ходы, не секунды</b><small>До подтверждения видна стоимость. Пока читаешь и думаешь, ничего не происходит.</small></div></div><div class="step"><i>♻</i><div><b>Собирай партиями по фракциям</b><small>Вместимость всех твоих мешков — 12 единиц. Сдача уже рассортированного груза на складе — 1 ход.</small></div></div><div class="step"><i>Л</i><div><b>Лена работает параллельно</b><small>Передай ей мешки за 1 ход. Она сдаст их и вернется к тебе, пока ты занят. Крупную стойку убирайте вдвоем.</small></div></div></div><div class="highlight">Обязательны поляна, пикник, сдача их находок и возврат капитана. Старая сцена, фото и артефакт — необязательные задания.</div><p>Баллы: за принятую единицу пластика +2, металла +3, стекла +2, бумаги +2, смешанного +1. Полный участок +10, фото +8, кубок +20, его история +10. За каждый оставшийся ход успешного соревновательного раунда +1.</p><p class="fine">Тарифы и правила упрощены для прототипа. Это не официальный регламент реального турнира. На экране нет настоящих соперников и общего рейтинга.</p>${btn('helpDone','Понятно')}`,'help');bind('helpDone',hide);}
 function records(){const r=saved.best;sheet('ЛИЧНЫЙ РЕЗУЛЬТАТ','Лучший план',r?`<div class="results"><div class="result-cell"><b>${r.score}</b><span>БАЛЛОВ</span></div><div class="result-cell"><b>${r.stars}/3</b><span>ЗВЕЗД</span></div><div class="result-cell"><b>${r.turn}</b><span>ХОДОВ</span></div></div><p>Сохраняется лучший завершенный раунд на 48 ходов. Прогулки без ограничений и незачтенные попытки не заменяют этот рекорд.</p>${btn('copyBest','Копировать рекорд')}`:'<p>Заверши раунд: убери поляну и пикник, сдай находки, вернись на склад. Тогда здесь появится лучший результат.</p>','records');bind('copyBest',()=>copyResult(r));}
 function menu(){if(busy){toast('Дождись завершения текущего действия.');return;}if(!inGame){help();return;}save();sheet('ПАУЗА / ХОДЫ НЕ ТРАТЯТСЯ','Обсудим план?',`<p>После праздника · ${s.relaxed?'прогулка':T.remaining(s)+' ходов осталось'}. Состояние мешков и поручение Лены сохраняются в этом браузере.</p>${btn('resume','Вернуться к маршруту')}${btn('menuTasks','Задания команды',true)}${btn('menuHelp','Управление и правила',true)}${btn('menuHome','Сохранить и в меню',true)}${btn('menuRestart','Начать этот раунд заново',true)}${btn('menuEnd','Зафиксировать текущий результат',true)}<p class="fine">Первая версия «Чистого маршрута» и «Чистый драйв» работают отдельно. Их сохранения эта игра не меняет.</p>`,'menu');bind('resume',hide);bind('menuTasks',tasks);bind('menuHelp',help);bind('menuHome',home);bind('menuRestart',()=>askStart(s.relaxed));bind('menuEnd',()=>confirmFinish(true));}
 bind('start',()=>saved.session?start(false,true):start(false));bind('practice',()=>askStart(true));bind('help',help);bind('records',records);bind('menu',menu);bind('mainAction',()=>selected===s.node?inspect():travel());bind('tasks',tasks);bind('goalStrip',tasks);bind('buddyButton',buddy);bind('bagButton',inventory);bind('zoomIn',()=>view.scale(1.25));bind('zoomOut',()=>view.scale(.8));bind('fit',()=>view.fit());bind('center',()=>view.center());
 document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal&&modal!=='brief'&&modal!=='result'){hide();return;}if(e.key==='Tab'&&modal){const bs=[...$('sheet').querySelectorAll('button:not(:disabled),textarea')];if(!bs.length)return;const first=bs[0],last=bs.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}if(!inGame||modal)return;if(e.key==='m'){view.fit();}if(e.key==='Escape')menu();if(e.key==='+')view.scale(1.2);if(e.key==='-')view.scale(.8);});
 window.addEventListener('pagehide',save);document.addEventListener('visibilitychange',()=>{if(document.hidden)save();});window.addEventListener('resize',()=>view.resize());if(window.ResizeObserver)new ResizeObserver(()=>view.resize()).observe($('stage'));
 function frame(ts){view.render(ts);requestAnimationFrame(frame);}requestAnimationFrame(frame);home();hud();
 if(new URLSearchParams(location.search).get('test')==='1')window.TeamTest={get state(){return s;},get saved(){return saved;},get view(){return view;},get busy(){return busy;},start,run,selectNode,inspect,travel,tasks,buddy,inventory,base,help,hide,photos,menu,home,collect,finishResult,history,restore:(raw)=>{const valid=T.restore(raw);if(!valid)throw Error('Invalid save');s=valid;inGame=true;selected=s.node;view.home=false;$('app').dataset.screen='game';hide();save();hud();}};
})();
